
package com.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthModule", targetNamespace = "http://basicCal.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthModule {


    /**
     * 
     * @param gender
     * @param weight
     * @param age
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bmrCalculator", targetNamespace = "http://basicCal.com/", className = "com.client.BmrCalculator")
    @ResponseWrapper(localName = "bmrCalculatorResponse", targetNamespace = "http://basicCal.com/", className = "com.client.BmrCalculatorResponse")
    @Action(input = "http://basicCal.com/HealthModule/bmrCalculatorRequest", output = "http://basicCal.com/HealthModule/bmrCalculatorResponse")
    public String bmrCalculator(
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "gender", targetNamespace = "")
        String gender,
        @WebParam(name = "height", targetNamespace = "")
        float height,
        @WebParam(name = "weight", targetNamespace = "")
        float weight);

    /**
     * 
     * @param gender
     * @param name
     * @param weight
     * @param id
     * @param age
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "display", targetNamespace = "http://basicCal.com/", className = "com.client.Display")
    @ResponseWrapper(localName = "displayResponse", targetNamespace = "http://basicCal.com/", className = "com.client.DisplayResponse")
    @Action(input = "http://basicCal.com/HealthModule/displayRequest", output = "http://basicCal.com/HealthModule/displayResponse")
    public String display(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "gender", targetNamespace = "")
        String gender,
        @WebParam(name = "weight", targetNamespace = "")
        float weight,
        @WebParam(name = "height", targetNamespace = "")
        float height,
        @WebParam(name = "age", targetNamespace = "")
        int age);

}
