
package com.basiscalc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HealthModule", targetNamespace = "http://basicCal.com/", wsdlLocation = "http://localhost:8080/ProjectWebServices/HealthModule?wsdl")
public class HealthModule_Service
    extends Service
{

    private final static URL HEALTHMODULE_WSDL_LOCATION;
    private final static WebServiceException HEALTHMODULE_EXCEPTION;
    private final static QName HEALTHMODULE_QNAME = new QName("http://basicCal.com/", "HealthModule");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProjectWebServices/HealthModule?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEALTHMODULE_WSDL_LOCATION = url;
        HEALTHMODULE_EXCEPTION = e;
    }

    public HealthModule_Service() {
        super(__getWsdlLocation(), HEALTHMODULE_QNAME);
    }

    public HealthModule_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEALTHMODULE_QNAME, features);
    }

    public HealthModule_Service(URL wsdlLocation) {
        super(wsdlLocation, HEALTHMODULE_QNAME);
    }

    public HealthModule_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEALTHMODULE_QNAME, features);
    }

    public HealthModule_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HealthModule_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HealthModule
     */
    @WebEndpoint(name = "HealthModulePort")
    public HealthModule getHealthModulePort() {
        return super.getPort(new QName("http://basicCal.com/", "HealthModulePort"), HealthModule.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HealthModule
     */
    @WebEndpoint(name = "HealthModulePort")
    public HealthModule getHealthModulePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://basicCal.com/", "HealthModulePort"), HealthModule.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEALTHMODULE_EXCEPTION!= null) {
            throw HEALTHMODULE_EXCEPTION;
        }
        return HEALTHMODULE_WSDL_LOCATION;
    }

}
