
package basiccalc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthModule", targetNamespace = "http://basicCalc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthModule {


    /**
     * 
     * @param gender
     * @param name
     * @param weight
     * @param id
     * @param age
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "display", targetNamespace = "http://basicCalc/", className = "basiccalc.Display")
    @ResponseWrapper(localName = "displayResponse", targetNamespace = "http://basicCalc/", className = "basiccalc.DisplayResponse")
    @Action(input = "http://basicCalc/HealthModule/displayRequest", output = "http://basicCalc/HealthModule/displayResponse")
    public String display(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "id", targetNamespace = "")
        long id,
        @WebParam(name = "gender", targetNamespace = "")
        String gender,
        @WebParam(name = "weight", targetNamespace = "")
        float weight,
        @WebParam(name = "height", targetNamespace = "")
        float height,
        @WebParam(name = "age", targetNamespace = "")
        int age);

    /**
     * 
     * @param gender
     * @param age
     * @param bmi
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateBodyFat", targetNamespace = "http://basicCalc/", className = "basiccalc.CalculateBodyFat")
    @ResponseWrapper(localName = "calculateBodyFatResponse", targetNamespace = "http://basicCalc/", className = "basiccalc.CalculateBodyFatResponse")
    @Action(input = "http://basicCalc/HealthModule/calculateBodyFatRequest", output = "http://basicCalc/HealthModule/calculateBodyFatResponse")
    public String calculateBodyFat(
        @WebParam(name = "gender", targetNamespace = "")
        String gender,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "bmi", targetNamespace = "")
        float bmi);

    /**
     * 
     * @param gender
     * @param weight
     * @param age
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateBMI", targetNamespace = "http://basicCalc/", className = "basiccalc.CalculateBMI")
    @ResponseWrapper(localName = "calculateBMIResponse", targetNamespace = "http://basicCalc/", className = "basiccalc.CalculateBMIResponse")
    @Action(input = "http://basicCalc/HealthModule/calculateBMIRequest", output = "http://basicCalc/HealthModule/calculateBMIResponse")
    public String calculateBMI(
        @WebParam(name = "weight", targetNamespace = "")
        float weight,
        @WebParam(name = "height", targetNamespace = "")
        float height,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "gender", targetNamespace = "")
        String gender);

    /**
     * 
     * @param gender
     * @param weight
     * @param age
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bmrCalculator", targetNamespace = "http://basicCalc/", className = "basiccalc.BmrCalculator")
    @ResponseWrapper(localName = "bmrCalculatorResponse", targetNamespace = "http://basicCalc/", className = "basiccalc.BmrCalculatorResponse")
    @Action(input = "http://basicCalc/HealthModule/bmrCalculatorRequest", output = "http://basicCalc/HealthModule/bmrCalculatorResponse")
    public String bmrCalculator(
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "gender", targetNamespace = "")
        String gender,
        @WebParam(name = "height", targetNamespace = "")
        float height,
        @WebParam(name = "weight", targetNamespace = "")
        float weight);

    /**
     * 
     * @param duration
     * @param metValue
     * @param heightCm
     * @param weightKg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "caloriesBurnRate", targetNamespace = "http://basicCalc/", className = "basiccalc.CaloriesBurnRate")
    @ResponseWrapper(localName = "caloriesBurnRateResponse", targetNamespace = "http://basicCalc/", className = "basiccalc.CaloriesBurnRateResponse")
    @Action(input = "http://basicCalc/HealthModule/caloriesBurnRateRequest", output = "http://basicCalc/HealthModule/caloriesBurnRateResponse")
    public String caloriesBurnRate(
        @WebParam(name = "weightKg", targetNamespace = "")
        double weightKg,
        @WebParam(name = "heightCm", targetNamespace = "")
        double heightCm,
        @WebParam(name = "duration", targetNamespace = "")
        double duration,
        @WebParam(name = "metValue", targetNamespace = "")
        double metValue);

    /**
     * 
     * @param heightCm
     * @param climate
     * @param weightKg
     * @param activityLevel
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dailyWaterIntakeCalculator", targetNamespace = "http://basicCalc/", className = "basiccalc.DailyWaterIntakeCalculator")
    @ResponseWrapper(localName = "dailyWaterIntakeCalculatorResponse", targetNamespace = "http://basicCalc/", className = "basiccalc.DailyWaterIntakeCalculatorResponse")
    @Action(input = "http://basicCalc/HealthModule/dailyWaterIntakeCalculatorRequest", output = "http://basicCalc/HealthModule/dailyWaterIntakeCalculatorResponse")
    public String dailyWaterIntakeCalculator(
        @WebParam(name = "weightKg", targetNamespace = "")
        double weightKg,
        @WebParam(name = "heightCm", targetNamespace = "")
        double heightCm,
        @WebParam(name = "activityLevel", targetNamespace = "")
        String activityLevel,
        @WebParam(name = "climate", targetNamespace = "")
        String climate);

}
